name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.vscode/**'
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: pnpm Audit
        run: pnpm audit --prod --audit-level=high

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run linting checks
        run: pnpm lint

      - name: Knip (production check)
        run: pnpm knip

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Run tests
        run: pnpm test

  deploy:
    name: Deploy
    needs: [lint, test, audit]
    runs-on: ubuntu-latest
    environment:
      name: production

    concurrency:
      group: 'deploy-${{ github.ref }}'
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup project
        uses: ./.github/actions/setup-project

      - name: Build
        run: pnpm build

      - name: Deploy to Firebase (Production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KNOBEL_MANAGER_WEBAPP }}
          channelId: live
          projectId: knobel-manager-webapp

      - name: Deploy Preview to Firebase (Pull Request)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KNOBEL_MANAGER_WEBAPP }}
          projectId: knobel-manager-webapp
